Шаблонизируй это
htmlacademy-ecmascript/1424419-cinemaddict-14 pull request #4
Opened 2021-04-06 14:51 UTC by Fumieizu

2021-04-06 14:54 UTC, Fumieizu commented
Не понял как скрывать попап и оставил как есть(с открытым)

2021-04-07 15:35 UTC, Shv-sergey70 requested changes

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +
Имя текущего файла содержит слово `mokc`. Должно быть `mock`

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  const filmPoster = [
1. Тут нарушается критерий Д17. Это должно быть за пределами функции (можно в текущем файле). 
2. Должно быть оформлено как константа
3. Так как это массив - имя должно быть во множественном числе

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  const filmTitle = [
Д17

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  return filmPoster[randomIndex];
Этот код дублируется c 31-33 строками. Стоит создать функцию для этой логики

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  const description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquet varius magna, non porta ligula feugiat eget. Fusce tristique felis at fermentum pharetra. Aliquam id orci
Д17

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  const rating = getRandomFloatNumber(0, 10, 1);
Переменная `rating` не нужна, можно сразу в `return` писать вызов функции

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +    minutes: getRandomInteger(0, 59),
Цифры стоит вынести в перечисления или константы

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  const genres = [
Д17

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  const maxDaysGap = 100;
Д17

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  const maxDaysGap = 100;
И аналогично ниже

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  return {
Тут можно использовать короткий синтаксис стрелочных функций без `return`

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/film.js
> +  return {
Тут можно использовать короткий синтаксис стрелочных функций без return

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/mokc/filter.js
> +    return {
Тут тоже можно коротким синтаксисом без `return`

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/view/film-card.js
> +  const mainGenre = genre.splice(0, 1).join('');
Может просто `genre[0]`?

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/view/film-popup.js
> +    : '';
Тут кода не много, можно все написать в одну строку

2021-04-07 15:35 UTC, Shv-sergey70 commented on src/view/film-popup.js
> +export const createFilmComment = (comment) => {
Деструктурировать можно сразу в параметре:
```
export const createFilmComment = ({text, emoji, commentator, commentTime}) => {
```

2021-04-09 12:56 UTC, merged